### PR TITLE
Cache improvements

### PR DESCRIPTION
**Pull request by Top-Cat**
The old BeatmapByHash method was uppercasing all hashes but then when they were added to the cache the api response was used which is currently always lowercase. This renders the cache useless.

Happy to standardise either way but this causes all hashes to be cached uppercase in BeatSaverSharper.

Additionally when maps have been updated they were only cached against their new hash. This PR adds a cache key for the hash used for the lookup.

### CODE REVIEW

**Comment by Auros** [comment]
test machine broke

**Comment by Top-Cat** [comment]
Oops

**Comment by Auros** [comment]
YO P;OG

**Comment by Top-Cat** [comment]
Ok, made the dictionary's case insensitive so that users can use lower or uppercase hashes freely

**Comment by Auros** [comment]
neat

**Pull request merged**
